## Cost DF

In [ ]:
import pandas as pd
eco_df = pd.read_csv('../raw data/Cost.csv')

C:\Users\User\AppData\Local\Temp\ipykernel_20620\54500614.py:2: DtypeWarning: Columns (43) have mixed types. Specify dtype option on import or set low_memory=False.
  eco_df = pd.read_csv('../datasets/Cost.csv')

In [37]:
eco_df.count()

Unnamed: 0                    13553
InvaCost_ID                   13553
Cost_ID                       13553
Repository                    12218
Reference_ID                  13553
                              ...
Overlap                         355
Benefit_value(s)              13553
Details                       11138
Initial contributors_names    13552
Double-checking               13553
Length: 67, dtype: int64

In [38]:
(eco_df['Official_country'] == 'Australia').sum()

np.int64(2597)

In [39]:
## To display all columns
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', None)

In [40]:
eco_df.head()

,Unnamed: 0,InvaCost_ID,Cost_ID,Repository,Reference_ID,Reference_title,Authors,Abstract,Publication_year,Language,Type_of_material,Previous_materials,Availability,Kingdom,Phylum,Class,Order,Family,Genus,Species,Subspecies,Common_name,Environment,Environment_IAS,HabitatVerbatim,Habitat,urbanArea,protectedArea,Island,Geographic_region,Official_country,State|Province|Administrative_area,Location,Spatial_scale,Period_of_estimation,Time_range,Probable_starting_year,Probable_ending_year,Probable_starting_year_adjusted,Probable_ending_year_adjusted,Occurrence,Raw_cost_estimate_original_currency,Min_Raw_cost_estimate_original_currency,Max_Raw_cost_estimate_original_currency,Raw_cost_estimate_2017_USD_exchange_rate,Raw_cost_estimate_2017_USD_PPP,Cost_estimate_per_year_original_currency,Cost_estimate_per_year_2017_USD_exchange_rate,Cost_estimate_per_year_2017_USD_PPP,Currency,Applicable_year,Type_of_applicable_year,Implementation,Acquisition_method,Impacted_sector,Type_of_cost,Type_of_cost_merged,Management_type,Method_reliability,Method_reliability_refined,Method_reliability_Explanation,Method_reliability_Expert_Name,Overlap,Benefit_value(s),Details,Initial contributors_names,Double-checking
0,0,IC_1.0_1,1,TC,2,Counting the Cost: Impact of Invasive Animals in Australia,McLeod,NaN,2004,English,Official report,"Rolfe, J., & Windle, J. (2014). Public preferences for controlling an invasive species in public and private spaces. Land Use Policy, 41, 1–10. https://doi.org/10.1016/j.landusepol.2014.04.013",Yes,Animalia,Chordata,Mammalia,Carnivora,Canidae,Vulpes,Vulpes vulpes,NaN,Red fox,Terrestrial,Terrestrial,NaN,NaN,other,NaN,Y,Oceania,Australia,NaN,Diverse/Unspecified,Country,2004,Year,2004,Unspecified,2004.0,2004.0,Potentially ongoing,17500000.0,NaN,NaN,1.670177e+07,1.663830e+07,17500000.0,1.670177e+07,1.663830e+07,AUD,2004,Publication year,Observed,Report/Estimation,Agriculture,Damage-Loss,Damage,NaN,High,NaN,NaN,NaN,NaN,no,Key loss is lamb predation. ABARE (2003) estimate 35 million lambs marked per year. Assumed 2% of all lambs marked are taken by foxes at a cost of $25 per head. See Saunders et al. (1997) for background of lamb predation,Christophe Diagne/Claire Assailly/Lise Nuninger,Yes
1,1,IC_1.0_2,2,TC,2,Counting the Cost: Impact of Invasive Animals in Australia,McLeod,NaN,2004,English,Official report,"Rolfe, J., & Windle, J. (2014). Public preferences for controlling an invasive species in public and private spaces. Land Use Policy, 41, 1–10. https://doi.org/10.1016/j.landusepol.2014.04.013",Yes,Animalia,Chordata,Mammalia,Carnivora,Canidae,Vulpes,Vulpes vulpes,NaN,Red fox,Terrestrial,Terrestrial,NaN,NaN,other,NaN,Y,Oceania,Australia,NaN,Diverse/Unspecified,Country,2004,Year,2004,Unspecified,2004.0,2004.0,Potentially ongoing,190000000.0,NaN,NaN,1.813335e+08,1.806444e+08,190000000.0,1.813335e+08,1.806444e+08,AUD,2004,Publication year,Observed,Report/Estimation,Environment,Damage-Loss,Damage,NaN,High,NaN,NaN,NaN,NaN,no,"Following the methodology in Pimentel et al. (2000), the impact of fox predation on the bird population in Australia is valued. (each bird valued 1$)",Christophe Diagne/Claire Assailly/Lise Nuninger,Yes
2,2,IC_1.0_3,3,TC,2,Counting the Cost: Impact of Invasive Animals in Australia,McLeod,NaN,2004,English,Official report,"Rolfe, J., & Windle, J. (2014). Public preferences for controlling an invasive species in public and private spaces. Land Use Policy, 41, 1–10. https://doi.org/10.1016/j.landusepol.2014.04.013",Yes,Animalia,Chordata,Mammalia,Carnivora,Canidae,Vulpes,Vulpes vulpes,NaN,Red fox,Terrestrial,Terrestrial,NaN,NaN,other,NaN,Y,Oceania,Australia,NaN,Tasmania,Site,2000,Year,2000,Unspecified,2000.0,2000.0,Potentially ongoing,16000000.0,NaN,NaN,1.527019e+07,1.521216e+07,16000000.0,1.527019e+07,1.521216e+07,AUD,2004,Publication year,Observed,Report/Estimation,Authorities-Stakeholders,Control,Management,Post-invasion_management,High,NaN,NaN,NaN,NaN,no,"Fox control expenditure in Tasmania of $9 million per year is also included (Tasmanian Dept. of Primary Industries, Water and Environment estimate). Original document not found\r\n--> J'ai remi McLeod en auteur , mais sinon le vrai auteur serai le Tasman Departmen (mais pas trouvé) ?",Christophe Diagne/Claire Assailly/Lise Nuninger,Yes
3,3,IC_1.0_4,4,TC,441,Non-indigenous vertebrates in Australia,Bomford and Hart,NaN,2002,English,Book chapter,"McLeod, R. (2004). Counting the Cost: Impact of Invasive Animals in Australia, 2004. Canberra. Retrieved from https://www.pestsmart.org.au/wp-content/uploads/2010/03/CountingTheCost.pdf",Yes,Animalia,Chordata,Mammalia,Carnivora,Canidae,Vulpes,Vulpes vulpes,NaN,Red fox,Terrestrial,Terrestrial,NaN,NaN,other,NaN,Y,Oceania,Australia,NaN,Diverse/Unspecified,Country,2000,Year,2000,Unspecified,2000.0,2000.0,Potentially ongoing,4000000.0,NaN,NaN,3.301105e+06,4.342785e+06,4000000.0,3.301105e+06,4.342785e+06,AUD,2000,Effective,Observed,Report/Estimation,Authorities-Stakeholders,Research,Management,Knowledge funding,Low,NaN,NaN,NaN,NaN,no,"4 000 000 research cost from Bomfort et al.\r\nThe methodology is shortly presented at the begining of the paper, but no details on cost calculations or sources.",Christophe Diagne/Claire Assailly/Lise Nuninger,Yes
4,4,IC_1.0_5,5,TC,441,Non-indigenous vertebrates in Australia,Bomford and Hart,NaN,2002,English,Book chapter,"McLeod, R. (2004). Counting the Cost: Impact of Invasive Animals in Australia, 2004. Canberra. Retrieved from https://www.pestsmart.org.au/wp-content/uploads/2010/03/CountingTheCost.pdf",Yes,Animalia,Chordata,Mammalia,Carnivora,Canidae,Vulpes,Vulpes vulpes,NaN,Red fox,Terrestrial,Terrestrial,NaN,NaN,other,NaN,Y,Oceania,Australia,NaN,Diverse/Unspecified,Country,2000,Year,2000,Unspecified,2000.0,2000.0,Potentially ongoing,2000000.0,NaN,NaN,1.650553e+06,2.171393e+06,2000000.0,1.650553e+06,2.171393e+06,AUD,2000,Effective,Observed,Report/Estimation,Authorities-Stakeholders,Control,Management,Post-invasion_management,Low,NaN,NaN,NaN,NaN,no,"﻿Governments are estimated to spend around $2 million on fox control annually. \r\nThe methodology is shortly presented at the begining of the paper, but no details on cost calculations or sources.",Christophe Diagne/Claire Assailly/Lise Nuninger,Yes

In [41]:
## Dataset now only has values from Australia
eco_df = eco_df[eco_df['Official_country'] == 'Australia']

In [42]:
eco_df[eco_df['Common_name'].str.contains('cat', case=False, na=False)].head(20)

,Unnamed: 0,InvaCost_ID,Cost_ID,Repository,Reference_ID,Reference_title,Authors,Abstract,Publication_year,Language,Type_of_material,Previous_materials,Availability,Kingdom,Phylum,Class,Order,Family,Genus,Species,Subspecies,Common_name,Environment,Environment_IAS,HabitatVerbatim,Habitat,urbanArea,protectedArea,Island,Geographic_region,Official_country,State|Province|Administrative_area,Location,Spatial_scale,Period_of_estimation,Time_range,Probable_starting_year,Probable_ending_year,Probable_starting_year_adjusted,Probable_ending_year_adjusted,Occurrence,Raw_cost_estimate_original_currency,Min_Raw_cost_estimate_original_currency,Max_Raw_cost_estimate_original_currency,Raw_cost_estimate_2017_USD_exchange_rate,Raw_cost_estimate_2017_USD_PPP,Cost_estimate_per_year_original_currency,Cost_estimate_per_year_2017_USD_exchange_rate,Cost_estimate_per_year_2017_USD_PPP,Currency,Applicable_year,Type_of_applicable_year,Implementation,Acquisition_method,Impacted_sector,Type_of_cost,Type_of_cost_merged,Management_type,Method_reliability,Method_reliability_refined,Method_reliability_Explanation,Method_reliability_Expert_Name,Overlap,Benefit_value(s),Details,Initial contributors_names,Double-checking
7,7,IC_1.0_8,8,TC,441,Non-indigenous vertebrates in Australia,Bomford and Hart,NaN,2002,English,Book chapter,"McLeod, R. (2004). Counting the Cost: Impact of Invasive Animals in Australia, 2004. Canberra. Retrieved from https://www.pestsmart.org.au/wp-content/uploads/2010/03/CountingTheCost.pdf",Yes,Animalia,Chordata,Mammalia,Carnivora,Felidae,Felis,Felis catus,NaN,Feral Cat,Terrestrial,Terrestrial,NaN,NaN,other,NaN,Y,Oceania,Australia,NaN,Diverse/Unspecified,Country,2000,Year,2000,Unspecified,2000.0,2000.0,Potentially ongoing,1000000.0,NaN,NaN,8.252764e+05,1.085696e+06,1.000000e+06,8.252764e+05,1.085696e+06,AUD,2000,Effective,Observed,Report/Estimation,Authorities-Stakeholders,Control,Management,Post-invasion_management,Low,NaN,NaN,NaN,NaN,no,"Governments are estimated to spend at least $1 million on feral cat control annually. Annual cat control research costs are also around $1 million per year.\r\nControl and research cost estimates are likely to be very conservative as they do not fully account for salaried positions and associated infrastructure.\r\nThe methodology is shortly presented at the begining of the paper, but no details on cost calculations or sources.",Christophe Diagne/Claire Assailly/Lise Nuninger,Yes
8,8,IC_1.0_9,9,TC,2,Counting the Cost: Impact of Invasive Animals in Australia,McLeod,NaN,2004,English,Official report,"Rolfe, J., & Windle, J. (2014). Public preferences for controlling an invasive species in public and private spaces. Land Use Policy, 41, 1–10. https://doi.org/10.1016/j.landusepol.2014.04.013",Yes,Animalia,Chordata,Mammalia,Carnivora,Felidae,Felis,Felis catus,NaN,Feral Cat,Terrestrial,Terrestrial,NaN,NaN,other,NaN,Y,Oceania,Australia,NaN,Diverse/Unspecified,Country,2004,Year,2004,Unspecified,2004.0,2004.0,Potentially ongoing,144000000.0,NaN,NaN,1.374317e+08,1.369094e+08,1.440000e+08,1.374317e+08,1.369094e+08,AUD,2004,Publication year,Potential,Report/Estimation,Public and social welfare,Personal loss,Damage,NaN,High,NaN,NaN,NaN,NaN,no,"Assumes 18 million cats, kill eight birds per year valued at $1 per bird (derived from Pimentel et al. 2000). Surveys outlined in the overview indicated a willingness to pay for biodiversity conservation and, correspondingly, a value of $1 per bird killed is included in the cost impact. Corresponding with the Pimentel et al. (2000) analysis, it is estimated that each cat kills eight birds per year (Willingness to pay)",Christophe Diagne/Claire Assailly/Lise Nuninger,Yes
70,70,IC_1.0_71,71,WoS,6487,Interior fences can reduce cost and uncertainty when eradicating invasive species from large islands,Bode et al,NaN,2013,English,Peer-reviewed article,NaN,Yes,Animalia,Chordata,Mammalia,Carnivora,Felidae,Felis,Felis catus,NaN,Feral Cat,Terrestrial,Terrestrial,NaN,NaN,other,NaN,Y,Oceania,Australia,NaN,Dirk Hartog Island\r\nArea (62 790 Ha),Site,Unspecified,Year,Unspecified,Unspecified,2013.0,2013.0,One-time,11500000.0,3700000.0,24200000.0,1.210041e+07,8.661407e+06,1.150000e+07,1.210041e+07,8.661407e+06,USD,2013,Publication year,Potential,Report/Estimation,Authorities-Stakeholders,Eradication,Management,Post-invasion_management,High,NaN,NaN,NaN,NaN,no,"Cost of eradication if no internal fence is built. \r\nCat eradication on Dirk Hartog Island, ""Our linear model estimates treatment costs at USD 11.5 M, with 95% confidence intervals of USD $3.7M and USD $24.2 M.""\r\nNo period specified",Christophe Diagne/Claire Assailly/Lise Nuninger,Yes
71,71,IC_1.0_72,72,WoS,6487,Interior fences can reduce cost and uncertainty when eradicating invasive species from large islands,Bode et al,NaN,2013,English,Peer-reviewed article,NaN,Yes,Animalia,Chordata,Mammalia,Carnivora,Felidae,Felis,Felis catus,NaN,Feral Cat,Terrestrial,Terrestrial,NaN,NaN,other,NaN,Y,Oceania,Australia,NaN,Dirk Hartog Island\r\nArea (62 790 Ha),Unit (Km),2013,Year,2013,2013,2013.0,2013.0,One-time,28000.0,NaN,NaN,2.946186e+04,2.108864e+04,2.800000e+04,2.946186e+04,2.108864e+04,USD,2013,Publication year,Potential,Report/Estimation,Authorities-Stakeholders,Control,Management,Post-invasion_management,High,NaN,NaN,NaN,NaN,no,"Add +20 000 $ for material at each boundary of the fence ""The cost for fence materials and construction is estimated at USD $28 000 per km. The two ends of any such fence – where it meets the ocean – are particularly vulnerable to incursions (Long&Rob- ley 2004). We therefore add an additional USD $10 000 at each boundary of each fence to account for the construction costs of additional structures.""\r\n--> value of cost ""USD 28 000/ km"" => Not found in Long&Robley 2004 (other values)",Christophe Diagne/Claire Assailly/Lise Nuninger,Yes
80,80,IC_1.0_81,81,TC,227,Cost effective feral animal exclusion fencing for areas of high conservation value in Australia - Part 2: Catalogue of fence designs,Long and Robley,NaN,2004,English,Official report,NaN,Yes,Animalia,Chordata,Mammalia,Carnivora/Lagomorpha,Canidae/Felidae/Leporidae,Felis/Oryctolagus/Vulpes,Felis catus/Oryctolagus cuniculus/Vulpes vulpes,NaN,Cat/Red fox/Rabbit,Terrestrial,Terrestrial,NaN,NaN,other,Y,Y,Oceania,Australia,NaN,Wardang Island/Currawinya National Park/Royal Botanic Gardens Cranbourne/Heirisson Prong/Watarrka National Park/Yaraandoo Environmental Centre/N.S.W Roads and Traffic Authority,Unit (Km),2004,Year,2004,2004,2004.0,2004.0,One-time,10000.0,9700.0,10300.0,9.543870e+03,9.507598e+03,1.000000e+04,9.543870e+03,9.507598e+03,AUD,2004,Effective,Observed,Report/Estimation,Authorities-Stakeholders,Control,Management,Post-invasion_management,High,NaN,NaN,NaN,NaN,no,"Cost of the fence material. \r\nFox + Feral cat + feral rabbit fences : $10,300/km or $9,700/km without the electric wires.\r\n",Christophe Diagne/Claire Assailly/Lise Nuninger,Yes
81,81,IC_1.0_82,82,TC,227,Cost effective feral animal exclusion fencing for areas of high conservation value in Australia - Part 2: Catalogue of fence designs,Long and Robley,NaN,2004,English,Official report,NaN,Yes,Animalia,Chordata,Mammalia,Carnivora/Lagomorpha,Canidae/Felidae/Leporidae,Felis/Oryctolagus/Vulpes,Felis catus/Oryctolagus cuniculus/Vulpes vulpes,NaN,Cat/Red fox/Rabbit,Terrestrial,Terrestrial,NaN,NaN,other,Y,Y,Oceania,Australia,NaN,Little Desert Lodge and Malleefowl Sanctuary/Scotia Sanctuary/Venus Bay Conservation Park/Peron Peninsula/Paruna Sanctuary/Ellenbrook Nature Reserve/Twin Swamps Nature Reserve,Unit (Km),2004,Year,2004,2004,2004.0,2004.0,One-time,9400.0,8900.0,9900.0,8.971238e+03,8.937142e+03,9.400000e+03,8.971238e+03,8.937142e+03,AUD,2004,Effective,Observed,Report/Estimation,Authorities-Stakeholders,Control,Management,Post-invasion_management,High,NaN,NaN,NaN,NaN,no,"Cost of the fence material. \r\nFox + Feral cat + feral rabbit fences : $10,300/km or $9,700/km without the electric wires.\r\n",Christophe Diagne/Claire Assailly/Lise Nuninger,Yes
82,82,IC_1.0_83,83,TC,227,Cost effective feral animal exclusion fencing for areas of high conservation value in Australia - Part 2: Catalogue of fence designs,Long and Robley,NaN,2004,English,Official report,NaN,Yes,Animalia,Chordata,Mammalia,Carnivora/Lagomorpha,Canidae/Felidae/Leporidae,Felis/Oryctolagus/Vulpes,Felis catus/Oryctolagus cuniculus/Vulpes vulpes,NaN,Cat/Red fox/Rabbit,Terrestrial,Terrestrial,NaN,NaN,other,Y,Y,Oceania,Australia,NaN,Calga Springs Sanctuary/Tidbinbilla Nature Reserve/Woodlands Historic Park and Hamilton Community Parklands/Cleland Wildlife Park,Unit (Km),2004,Year,2004,2004,2004.0,2004.0,One-time,10600.0,9800.0,11400.0,1.011650e+04,1.007805e+04,1.060000e+04,1.011650e+04,1.007805e+04,AUD,2004,Effective,Observed,Report/Estimation,Authorities-Stakeholders,Control,Management,Post-invasion_management,High,NaN,NaN,NaN,NaN,no,"Cost of the fence material. \r\nFox + Feral cat + feral rabbit fences : $10,300/km or $9,700/km without the electric wires.\r\n",Christophe Diagne/Claire Assailly/Lise Nuninger,Yes
83,83,IC_1.0_84,84,TC,227,Cost effective feral animal exclusion fencing for areas of high conservation value in Australia - Part 2: Catalogue of fence designs,Long and Robley,NaN,2004,English,Official report,NaN,Yes,Animalia,Chordata,Mammalia,Carnivora/Lagomorpha,Canidae/Felidae/Leporidae,Felis/Oryctolagus/Vulpes,Felis catus/Oryctolagus cuniculus/Vulpes vulpes,NaN,Cat/Red fox/Rabbit,Terrestrial,Terrestrial,NaN,NaN,other,Y,Y,Oceania,Australia,NaN,Yookamurra Sanctuary/Living Desert Wildlife Park/Karakamia,Unit (Km),2004,Year,2004,2004,2004.0,2004.0,One-time,8000.0,NaN,NaN,7.635096e+03,7.606078e+03,8.000000e+03,7.635096e+03,7.606078e+03,AUD,2004,Effective,Observed,Report/Estimation,Authorities-Stakeholders,Control,Management,Post-invasion_management,High,NaN,NaN,NaN,NaN,no,"Cost of the fence material. \r\nFox + Feral cat + feral rabbit fences : $10,300/km or $9,700/km without the electric wires.\r\n",Christophe Diagne/Claire Assailly/Lise Nuninger,Yes
88,88,IC_1.0_89,89,WoS,6487,Interior fences can reduce cost and uncertainty when eradicating invasive species from large islands,Bode et al,NaN,2013,English,Peer-reviewed article,NaN,Yes,Animalia,Chordata,Mammalia,Carnivora,Felidae,Felis,Felis catus,NaN,Feral Cat,Terrestrial,Terrestrial,NaN,NaN,other,NaN,Y,Oceania,Australia,NaN,Dirk Hartog Island\r\nArea (62 790 Ha),Site,Unspecified,Year,Unspecified,Unspecified,2013.0,2013.0,One-time,15750000.0,15400000.0,15900000.0,1.657229e+07,1.186236e+07,1.575000e+07,1.657229e+07,1.186236e+07,USD,2013,Publication year,Potential,Extrapolation,Authorities-Stakeholders,Eradication,Management,Post-invasion_management,High,NaN,NaN,NaN,NaN,no,"Eradication program of cats\r\nVarious eradiction costs according to the number of internal fences from 15.4 to 15.9 M, median = 15,75. Confidence intervals are provided in table 1.\r\n",Christophe Diagne/Claire Assailly/Lise Nuninger,Yes
89,89,IC_1.0_90,90,WoS,6487,Interior fences can reduce cost and uncertainty when eradicating invasive species from large islands,Bode et al,NaN,2013,English,Peer-reviewed article,NaN,Yes,Animalia,Chordata,Mammalia,Carnivora,Felidae,Felis,Felis catus,NaN,Feral Cat,Terrestrial,Terrestrial,NaN,NaN,other,Y,Y,Oceania,Australia,NaN,Faure Island,Site,Unspecified,Year,Unspecified,Unspecified,2013.0,2013.0,One-time,33700.0,NaN,NaN,3.545945e+04,2.538169e+04,3.370000e+04,3.545945e+04,2.538169e+04,USD,2013,Publication year,Observed,Report/Estimation,Authorities-Stakeholders,Eradication,Management,Post-invasion_management,High,NaN,NaN,NaN,NaN,no,"Eradication of cats in Faure Island years before (5800 Ha)\r\nValue ""corrected from inflation"", but no source given",Christophe Diagne/Claire Assailly/Lise Nuninger,Yes
141,141,IC_1.0_142,142,TC,501,Review of feral cat eradications on islands. Island Invasives: Eradication and Management,Campbell et al,NaN,2011,English,Book chapter,NaN,Yes,Animalia,Chordata,Mammalia,Carnivora,Felidae,Felis,Felis catus,NaN,Feral Cat,Terrestrial,Terrestrial,NaN,NaN,other,Y,Y,Oceania,Australia,NaN,Macquarie Island,Site,1975-2000,Period,1975,2000,1975.0,2000.0,One-time,2544000.0,NaN,NaN,2.906651e+06,2.584945e+06,9.784615e+04,1.117943e+05,9.942096e+04,USD,2009,Effective,Observed,Report/Estimation,Authorities-Stakeholders,Eradication,Management,Post-invasion_management,Low,NaN,NaN,NaN,130/202/361,no,"[Robinson, 2008, Personal communication] Cost of successful insular cat eradication campaigns. Costs converted by Campbell et al 2011.",Christophe Diagne/Claire Assailly/Lise Nuninger,Yes
144,144,IC_1.0_145,146,TC,297,"Eradication of feral cats on Faure Island, Western Australia",Algar et al,NaN,2010,English,Official report,"Parkes, J., & Murphy, E. (2003). Management of introduced mammals in New Zealand. New Zealand Journal of Zoology, 30(4), 335–359. https://doi.org/10.1080/03014223.2003.9518347",Yes,Animalia,Chordata,Mammalia,Carnivora,Felidae,Felis,Felis catus,NaN,Feral Cat,Terrestrial,Terrestrial,NaN,NaN,other,Y,Y,Oceania,Australia,NaN,Faure Island,Site,3 weeks,Year,Unspecified,Unspecified,2010.0,2010.0,One-time,26000.0,NaN,NaN,2.922700e+04,2.122274e+04,2.600000e+04,2.922700e+04,2.122274e+04,USD,2010,Publication year,Observed,Report/Estimation,Authorities-Stakeholders,Eradication,Management,Post-invasion_management,High,NaN,NaN,NaN,NaN,no,NOT FOUND IN ORIGINAL PAPER,Christophe Diagne/Claire Assailly/Lise Nuninger,Yes
150,150,IC_1.0_151,152,TC,570,"The efficacy of feral cat, fox and rabbit exclusion fence designs for threatened species protection",Morrison,NaN,2006,English,Peer-reviewed article,"Somers, M. J., & Hayward, M. W. (2012). Fencing for conservation: Restriction of evolutionary potential or a riposte to threatening processes? Fencing for Conservation: Restriction of Evolutionary Potential Or a Riposte to Threatening Processes?, 142(1), 1–320. https://doi.org/10.1007/978-1-4614-0902-1",Yes,Animalia,Chordata,Mammalia,Carnivora/Lagomorpha,Canidae/Felidae/Leporidae,Felis/Oryctolagus/Vulpes,Felis catus/Oryctolagus cuniculus/Vulpes vulpes,NaN,Cat/Red fox/Rabbit,Terrestrial,Terrestrial,NaN,NaN,other,NaN,Y,Oceania,Australia,NaN,NaN,Unit (Km),2005,Year,2005,2005,2005.0,2005.0,One-time,11669.5,NaN,NaN,1.118536e+04,1.054984e+04,1.166950e+04,1.118536e+04,1.054984e+04,AUD,2005,Effective,Observed,Report/Estimation,Authorities-Stakeholders,Control,Management,Post-invasion_management,High,NaN,NaN,NaN,NaN,no,"Material costs of exclusion fences; costs depend on the design. Punctual : fence building. No details on cost calculations or initial cost of each fence component is provided. However, fence design and product manufacturers are provided. ""﻿As of January 2005, fencing material costs per km were AUD $11,669.50 for Design 5, AUD $12,432 for Design 7 and AUD $8814.5 for Design 9."" Here we report the median value.",Christophe Diagne/Claire Assailly/Lise Nuninger,Yes
156,156,IC_1.0_157,158,WoS,9883,How to build an efficient conservation fence,Bode and Wintle,NaN,2010,English,Peer-reviewed article,NaN,Yes,Animalia,Chordata,Mammalia,Carnivora,Felidae,Felis,Felis catus,NaN,Feral Cat,Terrestrial,Terrestrial,NaN,NaN,other,NaN,Y,Oceania,Australia,NaN,NaN,Unit (Km),2010,Year,2010,2010,2010.0,2010.0,One-time,10825.0,NaN,NaN,1.116218e+04,8.105240e+03,1.082500e+04,1.116218e+04,8.105240e+03,AUD,2010,Publication year,Potential,Report/Estimation,Authorities-Stakeholders,Control,Management,Post-invasion_management,High,NaN,NaN,NaN,NaN,no,Fence designs = > Cost and effectiveness of six different predator-exclusion fence designs. \r\nHighest possible benefit-to-cost ratio (and also lowest probability of failure) => 10 825$/km\r\n(other designs = 7700 to 10825/km),Christophe Diagne/Claire Assailly/Lise Nuninger,Yes
160,160,IC_1.0_161,162,WoS,2388,Prioritizing eradication actions on islands: it's not all or nothing,Helmstedt et al,NaN,2016,English,Peer-reviewed article,NaN,Yes,Animalia,Chordata,Mammalia,Carnivora,Felidae,Felis,Felis catus,NaN,Feral Cat,Terrestrial,Terrestrial,NaN,NaN,other,Y,Y,Oceania,Australia,NaN,Faure Island,Unit (58 km2),Unspecified,Year,Unspecified,Unspecified,2016.0,2016.0,One-time,659043.0,NaN,NaN,5.003526e+05,4.530945e+05,6.590430e+05,5.003526e+05,4.530945e+05,AUD,2016,Publication year,Observed,Report/Estimation,Authorities-Stakeholders,Eradication,Management,Post-invasion_management,High,NaN,NaN,NaN,NaN,no,"The authors assessed that they have taken the individual eradication costs from Martin et al 2006 (ID WOS12448), but it was impossible to find these values in the original paper",Christophe Diagne/Claire Assailly/Lise Nuninger,Yes
164,164,IC_1.0_165,168,WoS,2388,Prioritizing eradication actions on islands: it's not all or nothing,Helmstedt et al,NaN,2016,English,Peer-reviewed article,NaN,Yes,Animalia,Chordata,Mammalia,Carnivora,Felidae,Felis,Felis catus,NaN,Feral Cat,Terrestrial,Terrestrial,NaN,NaN,other,NaN,Y,Oceania,Australia,NaN,Tasman Island,Unit (1.2 km2),Unspecified,Year,Unspecified,Unspecified,2016.0,2016.0,One-time,24395.0,NaN,NaN,1.852095e+04,1.677165e+04,2.439500e+04,1.852095e+04,1.677165e+04,AUD,2016,Publication year,Observed,Report/Estimation,Authorities-Stakeholders,Eradication,Management,Post-invasion_management,High,NaN,NaN,NaN,NaN,no,"The authors assessed that they have taken the individual eradication costs from Martin et al 2006 (ID WOS12448), but it was impossible to find these values in the original paper",Christophe Diagne/Claire Assailly/Lise Nuninger,Yes
165,165,IC_1.0_166,169,WoS,2388,Prioritizing eradication actions on islands: it's not all or nothing,Helmstedt et al,NaN,2016,English,Peer-reviewed article,NaN,Yes,Animalia,Chordata,Mammalia,Carnivora,Felidae,Felis,Felis catus,NaN,Feral Cat,Terrestrial,Terrestrial,NaN,NaN,other,NaN,Y,Oceania,Australia,NaN,Hermite,Unit (10.2 km2),Unspecified,Year,Unspecified,Unspecified,2016.0,2016.0,One-time,150672.0,NaN,NaN,1.143918e+05,1.035875e+05,1.506720e+05,1.143918e+05,1.035875e+05,AUD,2016,Publication year,Observed,Report/Estimation,Authorities-Stakeholders,Eradication,Management,Post-invasion_management,High,NaN,NaN,NaN,NaN,no,"The authors assessed that they have taken the individual eradication costs from Martin et al 2006 (ID WOS12448), but it was impossible to find these values in the original paper",Christophe Diagne/Claire Assailly/Lise Nuninger,Yes
167,167,IC_1.0_168,171,TC,307,Eradications of vertebrate pests in Australia,Gregory et al,NaN,2014,English,Official report,"Helmstedt, K. J., Shaw, J. D., Bode, M., Terauds, A., Springer, K., Robinson, S. A., & Possingham, H. P. (2016). Prioritizing eradication actions on islands: it’s not all or nothing. Journal of Applied Ecology, 53(3), 733–741. https://doi.org/10.1111/1365-2664.12599\r\n2388",Yes,Animalia,Chordata,Mammalia,Carnivora/Lagomorpha,Canidae/Felidae/Leporidae,Felis/Oryctolagus/Vulpes,Felis catus/Oryctolagus cuniculus/Vulpes vulpes,NaN,Cat/Red fox/Rabbit,Terrestrial,Terrestrial,NaN,NaN,other,Y,Y,Oceania,Australia,NaN,Mulligan Flat,Unit (485 Ha),2004,Year,2004,2004,2004.0,2004.0,One-time,1300000.0,NaN,NaN,1.213341e+06,9.267101e+05,1.300000e+06,1.213341e+06,9.267101e+05,AUD,2014,Publication year,Observed,Report/Estimation,Authorities-Stakeholders,Prevention,Management,Pre-invasion_management,High,NaN,NaN,NaN,NaN,no,"11.5 km long fence, encloses 485 Ha to protect plants. Enclosure has facilitated the removal of pest vertebrate predators, including foxes and cats. The enclosed rabbit population has also been targeted and has been dramatically reduced. Also limits the number of kangaroos (over grazing).",Christophe Diagne/Claire Assailly/Lise Nuninger,Yes

In [43]:
## Check where cats generally appear

eco_df.loc[
    eco_df['Common_name'].str.contains('cat', case=False, na=False),
    'Common_name'
].value_counts()

Common_name
Cat                                  20
rabbits, hares, cats                 18
Feral Cat                            15
Cats and foxes                        9
Cat/Red fox/Rabbit                    6
Feral cats                            4
Feral cats/Dingoes                    3
Predators (cats and foxes)            1
Felis catus/Oryctolagus cuniculus     1
Cat/Red fox                           1
Fox/Feral Cats                        1
Feral cat                             1
Name: count, dtype: int64

In [44]:
## How many rows do we have

len(eco_df)

2597

In [45]:
## Leave only rows. where cats appear
eco_df = eco_df[eco_df['Common_name'].str.contains('cat', case=False, na=False)]

len(eco_df)

80

In [46]:
eco_df.isna().sum()

Unnamed: 0                     0
InvaCost_ID                    0
Cost_ID                        0
Repository                     1
Reference_ID                   0
                              ..
Overlap                       78
Benefit_value(s)               0
Details                        1
Initial contributors_names     0
Double-checking                0
Length: 67, dtype: int64

In [47]:
eco_df.head()

,Unnamed: 0,InvaCost_ID,Cost_ID,Repository,Reference_ID,Reference_title,Authors,Abstract,Publication_year,Language,Type_of_material,Previous_materials,Availability,Kingdom,Phylum,Class,Order,Family,Genus,Species,Subspecies,Common_name,Environment,Environment_IAS,HabitatVerbatim,Habitat,urbanArea,protectedArea,Island,Geographic_region,Official_country,State|Province|Administrative_area,Location,Spatial_scale,Period_of_estimation,Time_range,Probable_starting_year,Probable_ending_year,Probable_starting_year_adjusted,Probable_ending_year_adjusted,Occurrence,Raw_cost_estimate_original_currency,Min_Raw_cost_estimate_original_currency,Max_Raw_cost_estimate_original_currency,Raw_cost_estimate_2017_USD_exchange_rate,Raw_cost_estimate_2017_USD_PPP,Cost_estimate_per_year_original_currency,Cost_estimate_per_year_2017_USD_exchange_rate,Cost_estimate_per_year_2017_USD_PPP,Currency,Applicable_year,Type_of_applicable_year,Implementation,Acquisition_method,Impacted_sector,Type_of_cost,Type_of_cost_merged,Management_type,Method_reliability,Method_reliability_refined,Method_reliability_Explanation,Method_reliability_Expert_Name,Overlap,Benefit_value(s),Details,Initial contributors_names,Double-checking
7,7,IC_1.0_8,8,TC,441,Non-indigenous vertebrates in Australia,Bomford and Hart,NaN,2002,English,Book chapter,"McLeod, R. (2004). Counting the Cost: Impact of Invasive Animals in Australia, 2004. Canberra. Retrieved from https://www.pestsmart.org.au/wp-content/uploads/2010/03/CountingTheCost.pdf",Yes,Animalia,Chordata,Mammalia,Carnivora,Felidae,Felis,Felis catus,NaN,Feral Cat,Terrestrial,Terrestrial,NaN,NaN,other,NaN,Y,Oceania,Australia,NaN,Diverse/Unspecified,Country,2000,Year,2000,Unspecified,2000.0,2000.0,Potentially ongoing,1000000.0,NaN,NaN,8.252764e+05,1.085696e+06,1000000.0,8.252764e+05,1.085696e+06,AUD,2000,Effective,Observed,Report/Estimation,Authorities-Stakeholders,Control,Management,Post-invasion_management,Low,NaN,NaN,NaN,NaN,no,"Governments are estimated to spend at least $1 million on feral cat control annually. Annual cat control research costs are also around $1 million per year.\r\nControl and research cost estimates are likely to be very conservative as they do not fully account for salaried positions and associated infrastructure.\r\nThe methodology is shortly presented at the begining of the paper, but no details on cost calculations or sources.",Christophe Diagne/Claire Assailly/Lise Nuninger,Yes
8,8,IC_1.0_9,9,TC,2,Counting the Cost: Impact of Invasive Animals in Australia,McLeod,NaN,2004,English,Official report,"Rolfe, J., & Windle, J. (2014). Public preferences for controlling an invasive species in public and private spaces. Land Use Policy, 41, 1–10. https://doi.org/10.1016/j.landusepol.2014.04.013",Yes,Animalia,Chordata,Mammalia,Carnivora,Felidae,Felis,Felis catus,NaN,Feral Cat,Terrestrial,Terrestrial,NaN,NaN,other,NaN,Y,Oceania,Australia,NaN,Diverse/Unspecified,Country,2004,Year,2004,Unspecified,2004.0,2004.0,Potentially ongoing,144000000.0,NaN,NaN,1.374317e+08,1.369094e+08,144000000.0,1.374317e+08,1.369094e+08,AUD,2004,Publication year,Potential,Report/Estimation,Public and social welfare,Personal loss,Damage,NaN,High,NaN,NaN,NaN,NaN,no,"Assumes 18 million cats, kill eight birds per year valued at $1 per bird (derived from Pimentel et al. 2000). Surveys outlined in the overview indicated a willingness to pay for biodiversity conservation and, correspondingly, a value of $1 per bird killed is included in the cost impact. Corresponding with the Pimentel et al. (2000) analysis, it is estimated that each cat kills eight birds per year (Willingness to pay)",Christophe Diagne/Claire Assailly/Lise Nuninger,Yes
70,70,IC_1.0_71,71,WoS,6487,Interior fences can reduce cost and uncertainty when eradicating invasive species from large islands,Bode et al,NaN,2013,English,Peer-reviewed article,NaN,Yes,Animalia,Chordata,Mammalia,Carnivora,Felidae,Felis,Felis catus,NaN,Feral Cat,Terrestrial,Terrestrial,NaN,NaN,other,NaN,Y,Oceania,Australia,NaN,Dirk Hartog Island\r\nArea (62 790 Ha),Site,Unspecified,Year,Unspecified,Unspecified,2013.0,2013.0,One-time,11500000.0,3700000.0,24200000.0,1.210041e+07,8.661407e+06,11500000.0,1.210041e+07,8.661407e+06,USD,2013,Publication year,Potential,Report/Estimation,Authorities-Stakeholders,Eradication,Management,Post-invasion_management,High,NaN,NaN,NaN,NaN,no,"Cost of eradication if no internal fence is built. \r\nCat eradication on Dirk Hartog Island, ""Our linear model estimates treatment costs at USD 11.5 M, with 95% confidence intervals of USD $3.7M and USD $24.2 M.""\r\nNo period specified",Christophe Diagne/Claire Assailly/Lise Nuninger,Yes
71,71,IC_1.0_72,72,WoS,6487,Interior fences can reduce cost and uncertainty when eradicating invasive species from large islands,Bode et al,NaN,2013,English,Peer-reviewed article,NaN,Yes,Animalia,Chordata,Mammalia,Carnivora,Felidae,Felis,Felis catus,NaN,Feral Cat,Terrestrial,Terrestrial,NaN,NaN,other,NaN,Y,Oceania,Australia,NaN,Dirk Hartog Island\r\nArea (62 790 Ha),Unit (Km),2013,Year,2013,2013,2013.0,2013.0,One-time,28000.0,NaN,NaN,2.946186e+04,2.108864e+04,28000.0,2.946186e+04,2.108864e+04,USD,2013,Publication year,Potential,Report/Estimation,Authorities-Stakeholders,Control,Management,Post-invasion_management,High,NaN,NaN,NaN,NaN,no,"Add +20 000 $ for material at each boundary of the fence ""The cost for fence materials and construction is estimated at USD $28 000 per km. The two ends of any such fence – where it meets the ocean – are particularly vulnerable to incursions (Long&Rob- ley 2004). We therefore add an additional USD $10 000 at each boundary of each fence to account for the construction costs of additional structures.""\r\n--> value of cost ""USD 28 000/ km"" => Not found in Long&Robley 2004 (other values)",Christophe Diagne/Claire Assailly/Lise Nuninger,Yes
80,80,IC_1.0_81,81,TC,227,Cost effective feral animal exclusion fencing for areas of high conservation value in Australia - Part 2: Catalogue of fence designs,Long and Robley,NaN,2004,English,Official report,NaN,Yes,Animalia,Chordata,Mammalia,Carnivora/Lagomorpha,Canidae/Felidae/Leporidae,Felis/Oryctolagus/Vulpes,Felis catus/Oryctolagus cuniculus/Vulpes vulpes,NaN,Cat/Red fox/Rabbit,Terrestrial,Terrestrial,NaN,NaN,other,Y,Y,Oceania,Australia,NaN,Wardang Island/Currawinya National Park/Royal Botanic Gardens Cranbourne/Heirisson Prong/Watarrka National Park/Yaraandoo Environmental Centre/N.S.W Roads and Traffic Authority,Unit (Km),2004,Year,2004,2004,2004.0,2004.0,One-time,10000.0,9700.0,10300.0,9.543870e+03,9.507598e+03,10000.0,9.543870e+03,9.507598e+03,AUD,2004,Effective,Observed,Report/Estimation,Authorities-Stakeholders,Control,Management,Post-invasion_management,High,NaN,NaN,NaN,NaN,no,"Cost of the fence material. \r\nFox + Feral cat + feral rabbit fences : $10,300/km or $9,700/km without the electric wires.\r\n",Christophe Diagne/Claire Assailly/Lise Nuninger,Yes

In [53]:
## Dropping Columns

cols_to_drop = ["Environment", "urbanArea", "Island",
                 "Cost_estimate_per_year_2017_USD_PPP", 'Currency', 
                 'Type_of_cost_merged', 'Benefit_value(s)', 'Time_range',
                   'Probable_starting_year', 'Probable_ending_year',
    'InvaCost_ID',
    'Cost_ID',
    'Unnamed: 0',
    'Repository',
    'Reference_ID',
    'Reference_title',
    'Authors',
    'Abstract',
    'Initial contributors_names',
    'Double-checking',
    'Overlap',
    'Method_reliability_Expert_Name',
    'Method_reliability_Explanation',
    'Method_reliability_refined',
    'Method_reliability',
    'Management_type',
    'Acquisition_method',
    'Implementation',
    'Type_of_applicable_year',
    'Occurrence',
    'Probable_starting_year_adjusted',
    'Probable_ending_year_adjusted',
    'Geographic_region',
    'Genus',
    'Family',
    'Order',
    'Class',
    'Phylum',
    'Kingdom',
    'Previous_materials',
    'Type_of_material',
    'Language',
    'Availability',
    'Subspecies',
    'Period_of_estimation',
    'Environment_IAS',
    'HabitatVerbatim',
    'Habitat',
    'Min_Raw_cost_estimate_original_currency',
    'Max_Raw_cost_estimate_original_currency',
    'protectedArea',
    'Raw_cost_estimate_original_currency',
    'Raw_cost_estimate_2017_USD_exchange_rate',
    'Raw_cost_estimate_2017_USD_PPP',
    'Spatial_scale',
    'Cost_estimate_per_year_original_currency'
]


eco_df = eco_df.drop(columns=cols_to_drop, errors='ignore')

In [54]:
eco_df.columns

Index(['Publication_year', 'Species', 'Common_name', 'Official_country',
       'State|Province|Administrative_area', 'Location',
       'Cost_estimate_per_year_2017_USD_exchange_rate', 'Applicable_year',
       'Impacted_sector', 'Type_of_cost', 'Details'],
      dtype='object')

In [50]:
## Types
eco_df.dtypes

Publication_year                                   int64
Species                                           object
Common_name                                       object
Official_country                                  object
State|Province|Administrative_area                object
Location                                          object
Cost_estimate_per_year_2017_USD_exchange_rate    float64
Applicable_year                                    int64
Impacted_sector                                   object
Type_of_cost                                      object
Details                                           object
dtype: object

In [51]:
# Missing Values
eco_df.isna().sum()

Publication_year                                  0
Species                                           0
Common_name                                       0
Official_country                                  0
State|Province|Administrative_area               33
Location                                          3
Cost_estimate_per_year_2017_USD_exchange_rate     2
Applicable_year                                   0
Impacted_sector                                   0
Type_of_cost                                      0
Details                                           1
dtype: int64

In [52]:
## Checking those rows where missing values

cols_to_check = [
    'Location',
    'Details',
    'Cost_estimate_per_year_2017_USD_exchange_rate',
    'Cost_estimate_per_year_2017_USD_PPP',
    'State|Province|Administrative_area'
]

rows_with_missing = eco_df[
    eco_df[cols_to_check].isna().any(axis=1)
]


rows_with_missing[
    cols_to_check + [
        'Official_country',
        'State|Province|Administrative_area',
        'Details',
        'Type_of_cost_merged'
    ]
]


rows_with_missing

KeyError: "['Cost_estimate_per_year_2017_USD_PPP'] not in index"

In [ ]:
## Drop 3 inconsistent rows (where the cost is nan and can influence on analysis)
eco_df = eco_df.dropna(
    subset=['Cost_estimate_per_year_2017_USD_PPP']
)

In [ ]:
## Check whther only 3 rows were dropped
len(eco_df)

77

In [ ]:
## In obj types of columns change Nan to Unspecified
eco_df[['State|Province|Administrative_area', 'Location', 'Details']] = (
    eco_df[['State|Province|Administrative_area', 'Location', 'Details']]
    .fillna('Unspecified')
)

In [ ]:
## Eliminate the rows that are connected to prey

kill_hunt_keywords = [
   'hunting',
   'hunt',
   'predation',
   'kill',
   'kills'
]

pattern = '|'.join(kill_hunt_keywords)

eco_df = eco_df[
    ~eco_df['Details']
        .str.lower()
        .str.contains(pattern, regex=True, na=False)
]

len(eco_df)

76

In [ ]:
## Check
predation_keywords = [
   'hunt',
   'predation',
   'kill',
   'kills'
   ]

pattern = '|'.join(predation_keywords)

predation_rows = eco_df[
    eco_df['Details']
        .str.lower()
        .str.contains(pattern, regex=True, na=False)
]

predation_rows[['Details']].head(20)

Empty DataFrame
Columns: [Details]
Index: []

In [ ]:
eco_df

,Publication_year,Species,Common_name,Environment,urbanArea,Island,Official_country,State|Province|Administrative_area,Location,Time_range,Probable_starting_year,Probable_ending_year,Cost_estimate_per_year_2017_USD_exchange_rate,Cost_estimate_per_year_2017_USD_PPP,Currency,Applicable_year,Impacted_sector,Type_of_cost,Type_of_cost_merged,Benefit_value(s),Details
7,2002,Felis catus,Feral Cat,Terrestrial,other,Y,Australia,Unspecified,Diverse/Unspecified,Year,2000,Unspecified,8.252764e+05,1.085696e+06,AUD,2000,Authorities-Stakeholders,Control,Management,no,"Governments are estimated to spend at least $1 million on feral cat control annually. Annual cat control research costs are also around $1 million per year.\r\nControl and research cost estimates are likely to be very conservative as they do not fully account for salaried positions and associated infrastructure.\r\nThe methodology is shortly presented at the begining of the paper, but no details on cost calculations or sources."
70,2013,Felis catus,Feral Cat,Terrestrial,other,Y,Australia,Unspecified,Dirk Hartog Island\r\nArea (62 790 Ha),Year,Unspecified,Unspecified,1.210041e+07,8.661407e+06,USD,2013,Authorities-Stakeholders,Eradication,Management,no,"Cost of eradication if no internal fence is built. \r\nCat eradication on Dirk Hartog Island, ""Our linear model estimates treatment costs at USD 11.5 M, with 95% confidence intervals of USD $3.7M and USD $24.2 M.""\r\nNo period specified"
71,2013,Felis catus,Feral Cat,Terrestrial,other,Y,Australia,Unspecified,Dirk Hartog Island\r\nArea (62 790 Ha),Year,2013,2013,2.946186e+04,2.108864e+04,USD,2013,Authorities-Stakeholders,Control,Management,no,"Add +20 000 $ for material at each boundary of the fence ""The cost for fence materials and construction is estimated at USD $28 000 per km. The two ends of any such fence – where it meets the ocean – are particularly vulnerable to incursions (Long&Rob- ley 2004). We therefore add an additional USD $10 000 at each boundary of each fence to account for the construction costs of additional structures.""\r\n--> value of cost ""USD 28 000/ km"" => Not found in Long&Robley 2004 (other values)"
80,2004,Felis catus/Oryctolagus cuniculus/Vulpes vulpes,Cat/Red fox/Rabbit,Terrestrial,other,Y,Australia,Unspecified,Wardang Island/Currawinya National Park/Royal Botanic Gardens Cranbourne/Heirisson Prong/Watarrka National Park/Yaraandoo Environmental Centre/N.S.W Roads and Traffic Authority,Year,2004,2004,9.543870e+03,9.507598e+03,AUD,2004,Authorities-Stakeholders,Control,Management,no,"Cost of the fence material. \r\nFox + Feral cat + feral rabbit fences : $10,300/km or $9,700/km without the electric wires.\r\n"
81,2004,Felis catus/Oryctolagus cuniculus/Vulpes vulpes,Cat/Red fox/Rabbit,Terrestrial,other,Y,Australia,Unspecified,Little Desert Lodge and Malleefowl Sanctuary/Scotia Sanctuary/Venus Bay Conservation Park/Peron Peninsula/Paruna Sanctuary/Ellenbrook Nature Reserve/Twin Swamps Nature Reserve,Year,2004,2004,8.971238e+03,8.937142e+03,AUD,2004,Authorities-Stakeholders,Control,Management,no,"Cost of the fence material. \r\nFox + Feral cat + feral rabbit fences : $10,300/km or $9,700/km without the electric wires.\r\n"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12110,2016,Diverse/Unspecified,"rabbits, hares, cats",Terrestrial,other,Y,Australia,South Australia,Yorke Peninsula coastal,Year,2011,2011,5.694082e+03,5.282024e+03,AUD,2016,Environment,Control,Management,no,Case Study 3: Yorke Peninsula Coastal
12111,2016,Diverse/Unspecified,"rabbits, hares, cats",Terrestrial,other,Y,Australia,South Australia,Yorke Peninsula coastal,Year,2012,2012,5.694082e+03,5.282024e+03,AUD,2016,Environment,Control,Management,no,Case Study 3: Yorke Peninsula Coastal
12112,2016,Diverse/Unspecified,"rabbits, hares, cats",Terrestrial,other,Y,Australia,South Australia,Yorke Peninsula coastal,Year,2013,2013,5.694082e+03,5.282024e+03,AUD,2016,Environment,Control,Management,no,Case Study 3: Yorke Peninsula Coastal
12113,2016,Diverse/Unspecified,"rabbits, hares, cats",Terrestrial,other,Y,Australia,South Australia,Yorke Peninsula coastal,Year,2014,2014,3.416449e+03,3.169214e+03,AUD,2016,Environment,Control,Management,no,Case Study 3: Yorke Peninsula Coastal
12114,2016,Diverse/Unspecified,"rabbits, hares, cats",Terrestrial,other,Y,Australia,South Australia,Yorke Peninsula coastal,Year,2015,2015,2.277633e+03,2.112809e+03,AUD,2016,Environment,Control,Management,no,Case Study 3: Yorke Peninsula Coastal

In [ ]:
## Raws that are related to Toxoplasmosis only

tox_keywords = [
    'toxoplasma',
    'toxoplasmosis',
    'toxoplasma gondii'
]

df_toxo_eco = eco_df[
    eco_df['Details']
    .str.lower()
    .str.contains('|'.join(tox_keywords), na=False)
]

In [ ]:
df_toxo_eco

,Publication_year,Species,Common_name,Environment,urbanArea,Island,Official_country,State|Province|Administrative_area,Location,Time_range,Probable_starting_year,Probable_ending_year,Cost_estimate_per_year_2017_USD_exchange_rate,Cost_estimate_per_year_2017_USD_PPP,Currency,Applicable_year,Impacted_sector,Type_of_cost,Type_of_cost_merged,Benefit_value(s),Details
11761,2020,Felis catus,Cat,Terrestrial,other,Y,Australia,Australia,Australia,Year,2019,2019,5.078819e+07,4.954361e+07,AUD,2019,Health,Control/Medical care,Mixed,no,Table 1: Summary of the annual medical and lost-productivity costs from acute toxoplasmosis
11762,2020,Felis catus,Cat,Terrestrial,other,Y,Australia,Australia,Australia,Year,2019,2019,1.479656e+08,1.443397e+08,AUD,2019,Health,Control/Medical care,Mixed,no,"Table 2: Summary of the medical, ongoing care and lost productivity costs from congenital Toxoplasmosis gondii infections"
11763,2020,Felis catus,Cat,Terrestrial,other,Y,Australia,Australia,Australia,Year,2019,2019,2.139503e+09,2.087074e+09,AUD,2019,Health,Control/Medical care,Mixed,no,Table 3: Summary of the costs from the impacts of Toxoplasmosis gondii infection on human behaviour and mental illness traffic accidents component
11764,2020,Felis catus,Cat,Terrestrial,other,Y,Australia,Australia,Australia,Year,2019,2019,1.639619e+09,1.599440e+09,AUD,2019,Health,Control/Medical care,Mixed,no,Table 3: Summary of the costs from the impacts of Toxoplasmosis gondii infection on human behaviour and mental illness suicides and suicide attempts
11765,2020,Felis catus,Cat,Terrestrial,other,Y,Australia,Australia,Australia,Year,2019,2019,5.278773e+07,5.149415e+07,AUD,2019,Health,Control/Medical care,Mixed,no,Table 3: Summary of the costs from the impacts of Toxoplasmosis gondii infection on human behaviour and mental illness schitzophrenia component
11766,2020,Felis catus,Cat,Terrestrial,other,Y,Australia,Australia,Australia,Year,2019,2019,6.645122e+06,6.482281e+06,AUD,2019,Agriculture,Damage-loss,Damage,no,Table 4: summary of theannual costs of Toxoplasma gondii induced abortions to the sheep industry in Australia

In [ ]:
## CATS only

cats_only_df = eco_df[
    eco_df['Common_name']
    .astype(str)
    .str.lower()
    .str.contains(r'\bcat\b', na=False) &
    ~eco_df['Common_name'].str.contains(r',|\+|/|;|\band\b', case=False, na=False)
]

cats_only_df

,Publication_year,Species,Common_name,Environment,urbanArea,Island,Official_country,State|Province|Administrative_area,Location,Time_range,Probable_starting_year,Probable_ending_year,Cost_estimate_per_year_2017_USD_exchange_rate,Cost_estimate_per_year_2017_USD_PPP,Currency,Applicable_year,Impacted_sector,Type_of_cost,Type_of_cost_merged,Benefit_value(s),Details
7,2002,Felis catus,Feral Cat,Terrestrial,other,Y,Australia,Unspecified,Diverse/Unspecified,Year,2000,Unspecified,8.252764e+05,1.085696e+06,AUD,2000,Authorities-Stakeholders,Control,Management,no,"Governments are estimated to spend at least $1 million on feral cat control annually. Annual cat control research costs are also around $1 million per year.\r\nControl and research cost estimates are likely to be very conservative as they do not fully account for salaried positions and associated infrastructure.\r\nThe methodology is shortly presented at the begining of the paper, but no details on cost calculations or sources."
70,2013,Felis catus,Feral Cat,Terrestrial,other,Y,Australia,Unspecified,Dirk Hartog Island\r\nArea (62 790 Ha),Year,Unspecified,Unspecified,1.210041e+07,8.661407e+06,USD,2013,Authorities-Stakeholders,Eradication,Management,no,"Cost of eradication if no internal fence is built. \r\nCat eradication on Dirk Hartog Island, ""Our linear model estimates treatment costs at USD 11.5 M, with 95% confidence intervals of USD $3.7M and USD $24.2 M.""\r\nNo period specified"
71,2013,Felis catus,Feral Cat,Terrestrial,other,Y,Australia,Unspecified,Dirk Hartog Island\r\nArea (62 790 Ha),Year,2013,2013,2.946186e+04,2.108864e+04,USD,2013,Authorities-Stakeholders,Control,Management,no,"Add +20 000 $ for material at each boundary of the fence ""The cost for fence materials and construction is estimated at USD $28 000 per km. The two ends of any such fence – where it meets the ocean – are particularly vulnerable to incursions (Long&Rob- ley 2004). We therefore add an additional USD $10 000 at each boundary of each fence to account for the construction costs of additional structures.""\r\n--> value of cost ""USD 28 000/ km"" => Not found in Long&Robley 2004 (other values)"
88,2013,Felis catus,Feral Cat,Terrestrial,other,Y,Australia,Unspecified,Dirk Hartog Island\r\nArea (62 790 Ha),Year,Unspecified,Unspecified,1.657229e+07,1.186236e+07,USD,2013,Authorities-Stakeholders,Eradication,Management,no,"Eradication program of cats\r\nVarious eradiction costs according to the number of internal fences from 15.4 to 15.9 M, median = 15,75. Confidence intervals are provided in table 1.\r\n"
89,2013,Felis catus,Feral Cat,Terrestrial,other,Y,Australia,Unspecified,Faure Island,Year,Unspecified,Unspecified,3.545945e+04,2.538169e+04,USD,2013,Authorities-Stakeholders,Eradication,Management,no,"Eradication of cats in Faure Island years before (5800 Ha)\r\nValue ""corrected from inflation"", but no source given"
141,2011,Felis catus,Feral Cat,Terrestrial,other,Y,Australia,Unspecified,Macquarie Island,Period,1975,2000,1.117943e+05,9.942096e+04,USD,2009,Authorities-Stakeholders,Eradication,Management,no,"[Robinson, 2008, Personal communication] Cost of successful insular cat eradication campaigns. Costs converted by Campbell et al 2011."
144,2010,Felis catus,Feral Cat,Terrestrial,other,Y,Australia,Unspecified,Faure Island,Year,Unspecified,Unspecified,2.922700e+04,2.122274e+04,USD,2010,Authorities-Stakeholders,Eradication,Management,no,NOT FOUND IN ORIGINAL PAPER
156,2010,Felis catus,Feral Cat,Terrestrial,other,Y,Australia,Unspecified,Unspecified,Year,2010,2010,1.116218e+04,8.105240e+03,AUD,2010,Authorities-Stakeholders,Control,Management,no,Fence designs = > Cost and effectiveness of six different predator-exclusion fence designs. \r\nHighest possible benefit-to-cost ratio (and also lowest probability of failure) => 10 825$/km\r\n(other designs = 7700 to 10825/km)
160,2016,Felis catus,Feral Cat,Terrestrial,other,Y,Australia,Unspecified,Faure Island,Year,Unspecified,Unspecified,5.003526e+05,4.530945e+05,AUD,2016,Authorities-Stakeholders,Eradication,Management,no,"The authors assessed that they have taken the individual eradication costs from Martin et al 2006 (ID WOS12448), but it was impossible to find these values in the original paper"
164,2016,Felis catus,Feral Cat,Terrestrial,other,Y,Australia,Unspecified,Tasman Island,Year,Unspecified,Unspecified,1.852095e+04,1.677165e+04,AUD,2016,Authorities-Stakeholders,Eradication,Management,no,"The authors assessed that they have taken the individual eradication costs from Martin et al 2006 (ID WOS12448), but it was impossible to find these values in the original paper"
165,2016,Felis catus,Feral Cat,Terrestrial,other,Y,Australia,Unspecified,Hermite,Year,Unspecified,Unspecified,1.143918e+05,1.035875e+05,AUD,2016,Authorities-Stakeholders,Eradication,Management,no,"The authors assessed that they have taken the individual eradication costs from Martin et al 2006 (ID WOS12448), but it was impossible to find these values in the original paper"
196,2006,Felis catus,Feral Cat,Terrestrial,other,Y,Australia,Unspecified,Macquarie Island,Year,2000,Unspecified,3.139774e+06,3.570444e+06,USD,2003,Authorities-Stakeholders,Eradication,Management,no,"[Copson, 2006, Personal communication] original reports not found (grey litterature), but the review seems good. Prices reajusted to US$ 2003"
290,2004,Felis catus,Feral Cat,Terrestrial,other,Y,Australia,Unspecified,Diverse/Unspecified,Year,1998,2003,7.157902e+05,7.130698e+05,AUD,2004,Authorities-Stakeholders,Control,Management,no,Labour cost of animal control
309,2012,Felis catus,Feral Cat,Terrestrial,other,Y,Australia,Unspecified,Kimberly,Period,2012,2032,1.934497e+05,1.213117e+05,AUD,2012,Authorities-Stakeholders,Control/Education,Management,no,"Ceasing the poison-baiting of dingoes on pastoral land (intact populations of Canis lupis dingo, a naturalized canid and Australia’s top terrestrial predator, regulate cat activity (Glen et al. 2007; Kennedy et al. 2011), education on the role of dingoes in trophic regulation, and cat spaying programs) based on expert elicitation"
10383,2017,Felis catus,Cat,Terrestrial,other,Y,Australia,Western Australia,Unspecified,Period,Unspecified,Unspecified,2.301423e+05,2.032279e+05,AUD,2017,Authorities-Stakeholders,Eradication,Management,no,"Table 1. Management eradication protocols for invasive species (Total costs).The islands\r\nhave a total area of 68,780 ha, ranging in size from\r\n0.002 to 23,569 ha, with most (591) smaller than\r\n1000 ha."
11761,2020,Felis catus,Cat,Terrestrial,other,Y,Australia,Australia,Australia,Year,2019,2019,5.078819e+07,4.954361e+07,AUD,2019,Health,Control/Medical care,Mixed,no,Table 1: Summary of the annual medical and lost-productivity costs from acute toxoplasmosis
11762,2020,Felis catus,Cat,Terrestrial,other,Y,Australia,Australia,Australia,Year,2019,2019,1.479656e+08,1.443397e+08,AUD,2019,Health,Control/Medical care,Mixed,no,"Table 2: Summary of the medical, ongoing care and lost productivity costs from congenital Toxoplasmosis gondii infections"
11763,2020,Felis catus,Cat,Terrestrial,other,Y,Australia,Australia,Australia,Year,2019,2019,2.139503e+09,2.087074e+09,AUD,2019,Health,Control/Medical care,Mixed,no,Table 3: Summary of the costs from the impacts of Toxoplasmosis gondii infection on human behaviour and mental illness traffic accidents component
11764,2020,Felis catus,Cat,Terrestrial,other,Y,Australia,Australia,Australia,Year,2019,2019,1.639619e+09,1.599440e+09,AUD,2019,Health,Control/Medical care,Mixed,no,Table 3: Summary of the costs from the impacts of Toxoplasmosis gondii infection on human behaviour and mental illness suicides and suicide attempts
11765,2020,Felis catus,Cat,Terrestrial,other,Y,Australia,Australia,Australia,Year,2019,2019,5.278773e+07,5.149415e+07,AUD,2019,Health,Control/Medical care,Mixed,no,Table 3: Summary of the costs from the impacts of Toxoplasmosis gondii infection on human behaviour and mental illness schitzophrenia component
11766,2020,Felis catus,Cat,Terrestrial,other,Y,Australia,Australia,Australia,Year,2019,2019,6.645122e+06,6.482281e+06,AUD,2019,Agriculture,Damage-loss,Damage,no,Table 4: summary of theannual costs of Toxoplasma gondii induced abortions to the sheep industry in Australia
11767,2020,Felis catus,Cat,Terrestrial,other,Y,Australia,South Australia,South Australia,Year,2019,2019,1.641013e+04,1.491654e+04,AUD,2018,Agriculture,Damage-loss,Damage,no,"Table 5: Estimates for the annual costs of macroscopic sarcocystosis to the sheep industry in Australia, by state: South Australia - Lamb"
11768,2020,Felis catus,Cat,Terrestrial,other,Y,Australia,South Australia,South Australia,Year,2019,2019,8.628084e+05,7.842788e+05,AUD,2018,Agriculture,Damage-loss,Damage,no,"Table 5: Estimates for the annual costs of macroscopic sarcocystosis to the sheep industry in Australia, by state: South Australia - Mutton"
11769,2020,Felis catus,Cat,Terrestrial,other,Y,Australia,New South Wales,New South Wales,Year,2019,2019,3.274733e+04,2.976679e+04,AUD,2018,Agriculture,Damage-loss,Damage,no,"Table 5: Estimates for the annual costs of macroscopic sarcocystosis to the sheep industry in Australia, by state: New South Wales- Lamb"
11770,2020,Felis catus,Cat,Terrestrial,other,Y,Australia,New South Wales,New South Wales,Year,2019,2019,1.254464e+04,1.140287e+04,AUD,2018,Agriculture,Damage-loss,Damage,no,"Table 5: Estimates for the annual costs of macroscopic sarcocystosis to the sheep industry in Australia, by state: New South Wales - Mutton"
11771,2020,Felis catus,Cat,Terrestrial,other,Y,Australia,Victoria,Victoria,Year,2019,2019,3.858205e+04,3.507045e+04,AUD,2018,Agriculture,Damage-loss,Damage,no,"Table 5: Estimates for the annual costs of macroscopic sarcocystosis to the sheep industry in Australia, by state: Victoria - Lamb"
11772,2020,Felis catus,Cat,Terrestrial,other,Y,Australia,Victoria,Victoria,Year,2019,2019,2.005683e+05,1.823133e+05,AUD,2018,Agriculture,Damage-loss,Damage,no,"Table 5: Estimates for the annual costs of macroscopic sarcocystosis to the sheep industry in Australia, by state: Victoria Mutton"
11773,2020,Felis catus,Cat,Terrestrial,other,Y,Australia,Queensland,Queensland,Year,2019,2019,2.516221e+02,2.287203e+02,AUD,2018,Agriculture,Damage-loss,Damage,no,"Table 5: Estimates for the annual costs of macroscopic sarcocystosis to the sheep industry in Australia, by state: Queensland - Mutton"
11774,2020,Felis catus,Cat,Terrestrial,other,Y,Australia,Western Australia,Western Australia,Year,2019,2019,9.189675e+03,8.353265e+03,AUD,2018,Agriculture,Damage-loss,Damage,no,"Table 5: Estimates for the annual costs of macroscopic sarcocystosis to the sheep industry in Australia, by state:Western Australia - Lamb"
11775,2020,Felis catus,Cat,Terrestrial,other,Y,Australia,Western Australia,Western Australia,Year,2019,2019,1.166943e+04,1.060732e+04,AUD,2018,Agriculture,Damage-loss,Damage,no,"Table 5: Estimates for the annual costs of macroscopic sarcocystosis to the sheep industry in Australia, by state: Western Australia - Mutton"
11776,2020,Felis catus,Cat,Terrestrial,other,Y,Australia,Tasmania,Tasmania,Year,2019,2019,3.442481e+04,3.129160e+04,AUD,2018,Agriculture,Damage-loss,Damage,no,"Table 5: Estimates for the annual costs of macroscopic sarcocystosis to the sheep industry in Australia, by state: Tasmania - Lamb"
11777,2020,Felis catus,Cat,Terrestrial,other,Y,Australia,Tasmania,Tasmania,Year,2019,2019,7.585129e+04,6.894758e+04,AUD,2018,Agriculture,Damage-loss,Damage,no,"Table 5: Estimates for the annual costs of macroscopic sarcocystosis to the sheep industry in Australia, by state: Tasmania - Mutton"
11778,2020,Felis catus,Cat,Terrestrial,other,Y,Australia,Australia,Australia,Year,2019,2019,3.639154e+06,3.549976e+06,AUD,2019,Health,Control/Medical care,Mixed,no,Costs of medical care and lost productivity from Cat transmitted Batronella henselae infection

In [ ]:
cats_only_df['Common_name'].value_counts()

Common_name
Cat          19
Feral Cat    14
Name: count, dtype: int64

In [ ]:
## Subset with multispecies
multi_species_df_eco = eco_df[
    eco_df['Common_name']
    .str.lower()
    .str.contains('cat', na=False) &
    eco_df['Common_name']
    .str.contains(',|\+| and |;', na=False)
]

multi_species_df_eco

,Publication_year,Species,Common_name,Environment,urbanArea,Island,Official_country,State|Province|Administrative_area,Location,Time_range,Probable_starting_year,Probable_ending_year,Cost_estimate_per_year_2017_USD_exchange_rate,Cost_estimate_per_year_2017_USD_PPP,Currency,Applicable_year,Impacted_sector,Type_of_cost,Type_of_cost_merged,Benefit_value(s),Details
386,2014,Diverse/Unspecified,Predators (cats and foxes),Terrestrial,other,Y,Australia,Unspecified,Aride zone of Australia,Year,2012,Unspecified,2022.930946,1268.573316,AUD,2012,Authorities-Stakeholders,Control,Management,no,"Most cost-efficient fence to protect bilbies against predators if enough land is available to reach the optimal separation of 40km between two fences. Cost includes eradication cost, maintenance, monitoring, construction cost). Comparison with other fence (ex single fence = $3000 (95% probabilities) to $8000 / bilby / year (5% probability)"
12078,2016,Diverse/Unspecified,Cats and foxes,Terrestrial,other,Y,Australia,South Australia,Adelaide hills,Year,2007,2007,3416.449005,3169.214174,AUD,2016,Environment,Control,Management,no,Case study 1: Adelaide Hills
12079,2016,Diverse/Unspecified,Cats and foxes,Terrestrial,other,Y,Australia,South Australia,Adelaide hills,Year,2008,2008,3416.449005,3169.214174,AUD,2016,Environment,Control,Management,no,Case study 1: Adelaide Hills
12080,2016,Diverse/Unspecified,Cats and foxes,Terrestrial,other,Y,Australia,South Australia,Adelaide hills,Year,2009,2009,3416.449005,3169.214174,AUD,2016,Environment,Control,Management,no,Case study 1: Adelaide Hills
12081,2016,Diverse/Unspecified,Cats and foxes,Terrestrial,other,Y,Australia,South Australia,Adelaide hills,Year,2010,2010,3416.449005,3169.214174,AUD,2016,Environment,Control,Management,no,Case study 1: Adelaide Hills
12082,2016,Diverse/Unspecified,Cats and foxes,Terrestrial,other,Y,Australia,South Australia,Adelaide hills,Year,2011,2011,3416.449005,3169.214174,AUD,2016,Environment,Control,Management,no,Case study 1: Adelaide Hills
12083,2016,Diverse/Unspecified,Cats and foxes,Terrestrial,other,Y,Australia,South Australia,Adelaide hills,Year,2012,2012,3416.449005,3169.214174,AUD,2016,Environment,Control,Management,no,Case study 1: Adelaide Hills
12084,2016,Diverse/Unspecified,Cats and foxes,Terrestrial,other,Y,Australia,South Australia,Adelaide hills,Year,2013,2013,3416.449005,3169.214174,AUD,2016,Environment,Control,Management,no,Case study 1: Adelaide Hills
12085,2016,Diverse/Unspecified,Cats and foxes,Terrestrial,other,Y,Australia,South Australia,Adelaide hills,Year,2014,2014,3416.449005,3169.214174,AUD,2016,Environment,Control,Management,no,Case study 1: Adelaide Hills
12086,2016,Diverse/Unspecified,Cats and foxes,Terrestrial,other,Y,Australia,South Australia,Adelaide hills,Year,2015,2015,3416.449005,3169.214174,AUD,2016,Environment,Control,Management,no,Case study 1: Adelaide Hills
12088,2016,Diverse/Unspecified,"rabbits, hares, cats",Terrestrial,other,Y,Australia,South Australia,Murray Mallee,Year,2007,2007,2277.632670,2112.809450,AUD,2016,Environment,Control,Management,no,Case study 2: Murray Mallee
12089,2016,Diverse/Unspecified,"rabbits, hares, cats",Terrestrial,other,Y,Australia,South Australia,Murray Mallee,Year,2008,2008,2277.632670,2112.809450,AUD,2016,Environment,Control,Management,no,Case study 2: Murray Mallee
12090,2016,Diverse/Unspecified,"rabbits, hares, cats",Terrestrial,other,Y,Australia,South Australia,Murray Mallee,Year,2009,2009,2277.632670,2112.809450,AUD,2016,Environment,Control,Management,no,Case study 2: Murray Mallee
12091,2016,Diverse/Unspecified,"rabbits, hares, cats",Terrestrial,other,Y,Australia,South Australia,Murray Mallee,Year,2010,2010,2277.632670,2112.809450,AUD,2016,Environment,Control,Management,no,Case study 2: Murray Mallee
12092,2016,Diverse/Unspecified,"rabbits, hares, cats",Terrestrial,other,Y,Australia,South Australia,Murray Mallee,Year,2011,2011,2277.632670,2112.809450,AUD,2016,Environment,Control,Management,no,Case study 2: Murray Mallee
12093,2016,Diverse/Unspecified,"rabbits, hares, cats",Terrestrial,other,Y,Australia,South Australia,Murray Mallee,Year,2012,2012,2277.632670,2112.809450,AUD,2016,Environment,Control,Management,no,Case study 2: Murray Mallee
12094,2016,Diverse/Unspecified,"rabbits, hares, cats",Terrestrial,other,Y,Australia,South Australia,Murray Mallee,Year,2013,2013,2277.632670,2112.809450,AUD,2016,Environment,Control,Management,no,Case study 2: Murray Mallee
12095,2016,Diverse/Unspecified,"rabbits, hares, cats",Terrestrial,other,Y,Australia,South Australia,Murray Mallee,Year,2014,2014,2277.632670,2112.809450,AUD,2016,Environment,Control,Management,no,Case study 2: Murray Mallee
12096,2016,Diverse/Unspecified,"rabbits, hares, cats",Terrestrial,other,Y,Australia,South Australia,Murray Mallee,Year,2015,2015,1138.816335,1056.404725,AUD,2016,Environment,Control,Management,no,Case study 2: Murray Mallee
12106,2016,Diverse/Unspecified,"rabbits, hares, cats",Terrestrial,other,Y,Australia,South Australia,Yorke Peninsula coastal,Year,2007,2007,5694.081675,5282.023624,AUD,2016,Environment,Control,Management,no,Case Study 3: Yorke Peninsula Coastal
12107,2016,Diverse/Unspecified,"rabbits, hares, cats",Terrestrial,other,Y,Australia,South Australia,Yorke Peninsula coastal,Year,2008,2008,5694.081675,5282.023624,AUD,2016,Environment,Control,Management,no,Case Study 3: Yorke Peninsula Coastal
12108,2016,Diverse/Unspecified,"rabbits, hares, cats",Terrestrial,other,Y,Australia,South Australia,Yorke Peninsula coastal,Year,2009,2009,5694.081675,5282.023624,AUD,2016,Environment,Control,Management,no,Case Study 3: Yorke Peninsula Coastal
12109,2016,Diverse/Unspecified,"rabbits, hares, cats",Terrestrial,other,Y,Australia,South Australia,Yorke Peninsula coastal,Year,2010,2010,5694.081675,5282.023624,AUD,2016,Environment,Control,Management,no,Case Study 3: Yorke Peninsula Coastal
12110,2016,Diverse/Unspecified,"rabbits, hares, cats",Terrestrial,other,Y,Australia,South Australia,Yorke Peninsula coastal,Year,2011,2011,5694.081675,5282.023624,AUD,2016,Environment,Control,Management,no,Case Study 3: Yorke Peninsula Coastal
12111,2016,Diverse/Unspecified,"rabbits, hares, cats",Terrestrial,other,Y,Australia,South Australia,Yorke Peninsula coastal,Year,2012,2012,5694.081675,5282.023624,AUD,2016,Environment,Control,Management,no,Case Study 3: Yorke Peninsula Coastal
12112,2016,Diverse/Unspecified,"rabbits, hares, cats",Terrestrial,other,Y,Australia,South Australia,Yorke Peninsula coastal,Year,2013,2013,5694.081675,5282.023624,AUD,2016,Environment,Control,Management,no,Case Study 3: Yorke Peninsula Coastal
12113,2016,Diverse/Unspecified,"rabbits, hares, cats",Terrestrial,other,Y,Australia,South Australia,Yorke Peninsula coastal,Year,2014,2014,3416.449005,3169.214174,AUD,2016,Environment,Control,Management,no,Case Study 3: Yorke Peninsula Coastal
12114,2016,Diverse/Unspecified,"rabbits, hares, cats",Terrestrial,other,Y,Australia,South Australia,Yorke Peninsula coastal,Year,2015,2015,2277.632670,2112.809450,AUD,2016,Environment,Control,Management,no,Case Study 3: Yorke Peninsula Coastal

In [ ]:
print("Toxoplasmosis rows:", len(df_toxo_eco))

print("Cats with other species rows:", len(multi_species_df_eco))

Toxoplasmosis rows: 6
Cats with other species rows: 28

In [ ]:
eco_df

,Publication_year,Species,Common_name,Environment,urbanArea,Island,Official_country,State|Province|Administrative_area,Location,Time_range,Probable_starting_year,Probable_ending_year,Cost_estimate_per_year_2017_USD_exchange_rate,Cost_estimate_per_year_2017_USD_PPP,Currency,Applicable_year,Impacted_sector,Type_of_cost,Type_of_cost_merged,Benefit_value(s),Details
7,2002,Felis catus,Feral Cat,Terrestrial,other,Y,Australia,Unspecified,Diverse/Unspecified,Year,2000,Unspecified,8.252764e+05,1.085696e+06,AUD,2000,Authorities-Stakeholders,Control,Management,no,"Governments are estimated to spend at least $1 million on feral cat control annually. Annual cat control research costs are also around $1 million per year.\r\nControl and research cost estimates are likely to be very conservative as they do not fully account for salaried positions and associated infrastructure.\r\nThe methodology is shortly presented at the begining of the paper, but no details on cost calculations or sources."
70,2013,Felis catus,Feral Cat,Terrestrial,other,Y,Australia,Unspecified,Dirk Hartog Island\r\nArea (62 790 Ha),Year,Unspecified,Unspecified,1.210041e+07,8.661407e+06,USD,2013,Authorities-Stakeholders,Eradication,Management,no,"Cost of eradication if no internal fence is built. \r\nCat eradication on Dirk Hartog Island, ""Our linear model estimates treatment costs at USD 11.5 M, with 95% confidence intervals of USD $3.7M and USD $24.2 M.""\r\nNo period specified"
71,2013,Felis catus,Feral Cat,Terrestrial,other,Y,Australia,Unspecified,Dirk Hartog Island\r\nArea (62 790 Ha),Year,2013,2013,2.946186e+04,2.108864e+04,USD,2013,Authorities-Stakeholders,Control,Management,no,"Add +20 000 $ for material at each boundary of the fence ""The cost for fence materials and construction is estimated at USD $28 000 per km. The two ends of any such fence – where it meets the ocean – are particularly vulnerable to incursions (Long&Rob- ley 2004). We therefore add an additional USD $10 000 at each boundary of each fence to account for the construction costs of additional structures.""\r\n--> value of cost ""USD 28 000/ km"" => Not found in Long&Robley 2004 (other values)"
80,2004,Felis catus/Oryctolagus cuniculus/Vulpes vulpes,Cat/Red fox/Rabbit,Terrestrial,other,Y,Australia,Unspecified,Wardang Island/Currawinya National Park/Royal Botanic Gardens Cranbourne/Heirisson Prong/Watarrka National Park/Yaraandoo Environmental Centre/N.S.W Roads and Traffic Authority,Year,2004,2004,9.543870e+03,9.507598e+03,AUD,2004,Authorities-Stakeholders,Control,Management,no,"Cost of the fence material. \r\nFox + Feral cat + feral rabbit fences : $10,300/km or $9,700/km without the electric wires.\r\n"
81,2004,Felis catus/Oryctolagus cuniculus/Vulpes vulpes,Cat/Red fox/Rabbit,Terrestrial,other,Y,Australia,Unspecified,Little Desert Lodge and Malleefowl Sanctuary/Scotia Sanctuary/Venus Bay Conservation Park/Peron Peninsula/Paruna Sanctuary/Ellenbrook Nature Reserve/Twin Swamps Nature Reserve,Year,2004,2004,8.971238e+03,8.937142e+03,AUD,2004,Authorities-Stakeholders,Control,Management,no,"Cost of the fence material. \r\nFox + Feral cat + feral rabbit fences : $10,300/km or $9,700/km without the electric wires.\r\n"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12110,2016,Diverse/Unspecified,"rabbits, hares, cats",Terrestrial,other,Y,Australia,South Australia,Yorke Peninsula coastal,Year,2011,2011,5.694082e+03,5.282024e+03,AUD,2016,Environment,Control,Management,no,Case Study 3: Yorke Peninsula Coastal
12111,2016,Diverse/Unspecified,"rabbits, hares, cats",Terrestrial,other,Y,Australia,South Australia,Yorke Peninsula coastal,Year,2012,2012,5.694082e+03,5.282024e+03,AUD,2016,Environment,Control,Management,no,Case Study 3: Yorke Peninsula Coastal
12112,2016,Diverse/Unspecified,"rabbits, hares, cats",Terrestrial,other,Y,Australia,South Australia,Yorke Peninsula coastal,Year,2013,2013,5.694082e+03,5.282024e+03,AUD,2016,Environment,Control,Management,no,Case Study 3: Yorke Peninsula Coastal
12113,2016,Diverse/Unspecified,"rabbits, hares, cats",Terrestrial,other,Y,Australia,South Australia,Yorke Peninsula coastal,Year,2014,2014,3.416449e+03,3.169214e+03,AUD,2016,Environment,Control,Management,no,Case Study 3: Yorke Peninsula Coastal
12114,2016,Diverse/Unspecified,"rabbits, hares, cats",Terrestrial,other,Y,Australia,South Australia,Yorke Peninsula coastal,Year,2015,2015,2.277633e+03,2.112809e+03,AUD,2016,Environment,Control,Management,no,Case Study 3: Yorke Peninsula Coastal

In [ ]:
eco_df.to_csv("eco_df_clean.csv", index=False)

In [ ]:
from ydata_profiling import ProfileReport
ProfileReport(eco_df)

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

100%|██████████| 21/21 [00:00<00:00, 42.30it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]